options(unzip = "internal")
install.packages("devtools")
devtools::install_github("hadley/devtools")
install.packages("shiny")
install.packages("ggplot2")
install.packages("RPostgreSQL")
install.packages("dplyr")
devtools::install_github("gaborcsardi/falsy")
devtools::install_github("gaborcsardi/dotenv")
devtools::install_github("hadley/rvest")
devtools::install_github("cwarden/amazonuserstatr")
