options(unzip = "internal")
install.packages("httr")
install.packages("RPostgreSQL")
install.packages("dplyr")
install.packages("devtools")
install.packages("ggplot2")
install.packages("shiny")
devtools::install_github("hadley/devtools")
devtools::install_github("gaborcsardi/falsy")
devtools::install_github("gaborcsardi/dotenv")
devtools::install_github("hadley/rvest")
devtools::install_github("cwarden/amazonuserstatr")
